import { useEffect, useState } from 'react';
import { useAppState } from '../lib/AppState';
import { api } from '../lib/api';
import type { ExecutiveBriefing, RegionalSummary } from '../types';
import {
  Activity,
  AlertTriangle,
  CheckCircle2,
  ChevronDown,
  Printer,
  ShieldAlert,
  TreePine,
  Users,
} from 'lucide-react';

export function ExecutiveBriefingPage() {
  const { regions, selectedRegion, setSelectedRegion } = useAppState();
  const [briefing, setBriefing] = useState<ExecutiveBriefing | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const r = selectedRegion ?? regions[0]?.region_id;
    if (!r && regions.length === 0) return;
    setLoading(true);
    api
      .executiveBriefing(r ?? null)
      .then(setBriefing)
      .finally(() => setLoading(false));
  }, [selectedRegion, regions]);

  const region = regions.find((x) => x.region_id === selectedRegion) ?? null;

  return (
    <div className="h-full overflow-y-auto px-8 py-6 space-y-5 print:px-0 print:py-0">
      <div className="flex items-end justify-between print:hidden">
        <div>
          <p className="text-xs uppercase tracking-wider text-muted">Executive briefing</p>
          <h1 className="text-2xl font-semibold tracking-tight">
            {region?.region_name ?? 'All Queensland'}
          </h1>
          <p className="text-sm text-muted">
            Generated by Grid Operations Advisor — grounded in gold tables and inspection documents.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="relative">
            <select
              value={selectedRegion ?? ''}
              onChange={(e) => setSelectedRegion(e.target.value || null)}
              className="appearance-none panel-soft text-sm pl-3 pr-8 py-2 border border-border/40 rounded-md"
            >
              <option value="">All Queensland</option>
              {regions.map((r) => (
                <option key={r.region_id} value={r.region_id}>
                  {r.region_name}
                </option>
              ))}
            </select>
            <ChevronDown className="w-3.5 h-3.5 absolute right-2.5 top-1/2 -translate-y-1/2 text-muted pointer-events-none" />
          </div>
          <button className="btn-secondary text-sm" onClick={() => window.print()}>
            <Printer className="w-3.5 h-3.5" />
            Export
          </button>
        </div>
      </div>

      {loading && (
        <div className="panel p-10 text-center text-muted">Drafting briefing…</div>
      )}

      {briefing && !loading && (
        <>
          <div className="panel p-6 space-y-4">
            <div className="flex items-center gap-2">
              <Activity className="w-4 h-4 text-electric-cyan" />
              <h2 className="text-sm font-semibold tracking-tight uppercase text-muted">
                Headline
              </h2>
            </div>
            <h3 className="text-xl font-semibold leading-snug">{briefing.headline}</h3>
            <p className="text-sm leading-relaxed text-text-secondary whitespace-pre-wrap">
              {briefing.summary}
            </p>
            <div className="grid grid-cols-3 gap-3 pt-4 border-t border-border/30">
              <Kpi
                label="Customer impact reduction"
                value={briefing.estimated_customer_impact_reduction.toLocaleString()}
                icon={<Users className="w-4 h-4 text-electric-cyan" />}
              />
              <Kpi
                label="Top risk zones"
                value={briefing.top_risk_zones.length.toString()}
                icon={<ShieldAlert className="w-4 h-4 text-critical-red" />}
              />
              <Kpi
                label="Open decisions"
                value={briefing.open_decisions.length.toString()}
                icon={<AlertTriangle className="w-4 h-4 text-risk-amber" />}
              />
            </div>
          </div>

          <div className="grid grid-cols-5 gap-3">
            {briefing.top_risk_zones.slice(0, 5).map((zone: RegionalSummary) => (
              <div className="kpi" key={zone.region_id}>
                <div className="kpi-label">{zone.region_name}</div>
                <div className="kpi-value text-critical-red">
                  {zone.critical_risk_assets + zone.high_risk_assets}
                </div>
                <div className="text-[11px] text-muted">
                  {zone.critical_risk_assets} critical • {zone.high_risk_assets} high
                </div>
              </div>
            ))}
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div className="panel p-5 col-span-2 space-y-3">
              <h3 className="text-sm font-semibold tracking-tight flex items-center gap-2">
                <ShieldAlert className="w-4 h-4 text-critical-red" />
                Top risk zones
              </h3>
              <div className="space-y-2">
                {briefing.top_risk_zones.map((zone: RegionalSummary) => (
                  <div
                    key={zone.region_id}
                    className="panel-soft p-3 grid grid-cols-[1fr_auto] gap-3"
                  >
                    <div>
                      <div className="text-sm font-semibold">{zone.region_name}</div>
                      <div className="text-[11px] text-muted font-mono">{zone.region_id}</div>
                      <div className="grid grid-cols-3 gap-3 mt-2 text-xs">
                        <Stat
                          label="High"
                          value={zone.high_risk_assets.toString()}
                          tint="text-risk-amber"
                        />
                        <Stat
                          label="Critical"
                          value={zone.critical_risk_assets.toString()}
                          tint="text-critical-red"
                        />
                        <Stat
                          label="Veg backlog"
                          value={zone.vegetation_backlog.toString()}
                          tint="text-vegetation-green"
                        />
                      </div>
                    </div>
                    <div className="text-right text-xs">
                      <div className="kpi-label">Customers at risk</div>
                      <div className="text-base font-mono">
                        {zone.customers_at_risk.toLocaleString()}
                      </div>
                      <div className="kpi-label mt-1">Critical customers</div>
                      <div className="text-base font-mono">
                        {zone.critical_customer_count_exposed.toLocaleString()}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="panel p-5 space-y-3">
              <h3 className="text-sm font-semibold tracking-tight flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-vegetation-green" />
                Recommended actions
              </h3>
              <ol className="space-y-3 text-sm text-text-secondary">
                {briefing.top_recommended_actions.map((a, i) => (
                  <li key={i} className="leading-snug">
                    <div className="flex items-start gap-2">
                      <span className="text-electric-cyan font-mono text-xs mt-0.5">{i + 1}.</span>
                      <div>
                        <div className="text-text-primary text-[13px] font-medium">
                          {a.region_name}
                        </div>
                        <div className="text-xs text-text-secondary mt-0.5">{a.headline}</div>
                        <div className="text-[11px] text-muted mt-1">
                          Impact reduction:{' '}
                          <span className="text-text-primary font-mono">
                            {a.estimated_customer_impact_reduction.toLocaleString()}
                          </span>{' '}
                          customers
                        </div>
                      </div>
                    </div>
                  </li>
                ))}
              </ol>
            </div>
          </div>

          <div className="panel p-5 space-y-3">
            <h3 className="text-sm font-semibold tracking-tight flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 text-risk-amber" />
              Open decisions
            </h3>
            <ul className="space-y-2 text-sm text-text-secondary">
              {briefing.open_decisions.map((d, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-risk-amber">•</span>
                  <span>{d}</span>
                </li>
              ))}
            </ul>
            <div className="pt-3 border-t border-border/30 text-[11px] text-muted">
              Generated {briefing.generated_at}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

function Kpi({
  label,
  value,
  icon,
}: {
  label: string;
  value: string;
  icon: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex items-center justify-between text-muted">
        <span className="kpi-label">{label}</span>
        {icon}
      </div>
      <div className="text-2xl font-semibold mt-1">{value}</div>
    </div>
  );
}

function Stat({ label, value, tint }: { label: string; value: string; tint: string }) {
  return (
    <div>
      <div className="kpi-label">{label}</div>
      <div className={`text-base font-mono ${tint}`}>{value}</div>
    </div>
  );
}
